### ISSUE TITLE
Look into the WebViews we should support

### ISSUE THREAD

**Issue by RupertBenWiser** [WebView-CG/Compatibility-Data-Project#2]
We are aiming to spend roughly a year on this project. What WebViews should we prioritize?

**Comment by aluhrs13** [comment]
Thinking of top WebView for each OS:
- Windows: [WebView2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/)
- MacOS & iOS: [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview)
- Linux: [WebKitGTK](https://webkitgtk.org/) (not 100% confident this is the "top" one)
- Android: [WebView](https://developer.android.com/reference/android/webkit/WebView)

Some interesting conversation topics:
- Android's [Custom Tabs](https://developer.chrome.com/docs/android/custom-tabs)
- MacOS & iOS also have [SFSafariViewController](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller)
- [Electron](https://www.electronjs.org/) is somewhat debatably a WebView?

**Comment by RupertBenWiser** [comment]
Yeah I think understanding what the core difference between a WebView, vs an embedded engine like Electron (if there really is one), would be super helpful to dive into.  [Sangwhan Moon](https://beta.sangwhan.com/about) drove a session last year about the [future of powerful APIs](https://github.com/w3c/tpac2023-breakouts/issues/76) somewhat around technologies - I can see some cross pollination opportunities there. Perhaps we should track that as its own issue?

**Comment by Elchi3** [comment]
fwiw, currently, the mdn/browser-compat-data project only contains data for the Chrome Android WebView. The project describes rules for adding additional browsers to the data: https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines/browsers.md#addition-of-browsers that might be interesting to you in case you would plan on recording more compat data in the BCD project.

**Comment by abhijeetk** [comment]
Similar to Electron, [CEF ](https://bitbucket.org/chromiumembedded/cef/src/master/)is also a interesting project to cosider.
It provides a C-APIs which allow developers to develop application is various languages(C#, Go,Python)
Automotive industry adpting a CEF : https://www.youtube.com/watch?v=8zrLCGjwJ3k

**Comment by LauraWebdev** [comment]
Supporting Webkit2GTK for Linux is probably the best bet, projects like [Photino](https://github.com/tryphotino/photino.NET/) and [Tauri](https://tauri.app/v1/references/webview-versions/) as well as other native software use it. It's definitely useful, as features like Gamepad API are still not supported in relatively recent stable versions.

**Comment by RupertBenWiser** [comment]
We have settled on WKWebView, Android WebView, and WebView2 for the time being. I'm going to close this issue, if anyone wishes to have any other WebViews added, please open an issue for it and we will discuss it.
