### ISSUE TITLE
Notifications API

### ISSUE THREAD

**Issue by NiklasMerz** [WebView-CG/Compatibility-Data-Project#21]
>How timely. I was just trying to figure out how Webviews handled browser notifications yesterday (they don't which is obvious in hindsight I guess). That one doesn't yet resolve on this site, but I've bookmarked it

https://news.ycombinator.com/item?id=40284147#40284667

**Comment by RupertBenWiser** [comment]
Somewhat implemented on this page now:
https://caniwebview.com/features/notification/

I think the path forward here is to get better data for WKWebView and WebView2 on [bcd](https://github.com/mdn/browser-compat-data).

cc @aluhrs13 who might have thoughts on this topic
