### ISSUE TITLE
Record TPAC demo on Can I WebView?

### ISSUE THREAD

**Issue by dontcallmedom** [WebView-CG/Compatibility-Data-Project#27]
As in other recent years, groups participating to TPAC are invited to submit recorded videos of demos or updates on their work: https://www.w3.org/wiki/TPAC/2024/Demos_and_Group_updates

See for instance the videos submitted in 2023 https://www.w3.org/2023/09/TPAC/group-updates.html (including the [WebDX one on Web Features](https://www.w3.org/2023/09/TPAC/demos/web-features.html)).

As I suggested on the [call today](https://docs.google.com/document/d/17xTpRYB8yFQF_rSOOj9aUpiJItZXGmNEf77faejMHPo/edit#heading=h.fhjmwx7p75i8), I think it might be interesting to take advantage of that opportunity to present the work of the WebViews CG, likely by starting from Can I WebView - such a video could present the Web site, discuss both how WebViews different from regular Web browsers by looking at one of the documented behaviors (possibly including how they differ from one another as well), and discuss how the coverage of APIs in WebViews differ from browsers (possibly as we discussed by showing the diff of what Baseline coverage looks like in a WebView vs in regular Web browsers).

The wiki page above links to best practices for these videos, as well as the expected timeline.

**Comment by RupertBenWiser** [comment]
Thanks a ton for reaching out Dom! @NiklasMerz and I had a chat about this and we're not sure we have the capacity to prioritize this.

I'll leave this issue open until the next group meeting but we likely won't be able to record a demo this year.
